name: learning-py
channels:
  - conda-forge
dependencies:
  - python=3.7
  - tensorflow=1.15
  - scikit-learn=1.0
  - tf2onnx=1.9
  - numpy=1.21
  - jupyterlab=3
  - bazel=5.1.1
  - pip:
      - jupytext
      - jupyterlab-vim
      - jupyterlab-vimrc
      - jedi-language-server
      - python-lsp-server
