[config]
skip_core_tasks = true

[tasks.build]
cwd = "wasm-rs"
script_runner = "@shell"
script = """
    wasm-pack build --target web -d ../pkg --release
"""

[tasks.run]
cwd = "wasm-rs"
script_runner = "@shell"
script = """
    wasm-pack build --target web -d ../pkg --release
    yarn run dev
"""

[tasks.clean]
cwd = "wasm-rs"
script_runner = "@shell"
script = """
    yarn run clean
    cargo clean
"""